### ISSUE TITLE
0.2.2 Release checklist

### ISSUE THREAD

**Issue by cgewecke** [cgewecke/eth-gas-reporter#123]
- [x] Start writing release notes in addition to changelog
- [x] Add buidler plugin instructions 
- [x] Add proxy resolver, address resolver hook instructions 
- [x] Add codechecks instructions
